#!/bin/sh

set -e
set -x
cd python
echo | python nuc.py -c 2 runtests.fs
echo | python nuc.py -c 4 runtests.fs
echo | python nuc.py -c 8 runtests.fs
echo | python nuc.py -c 2 -b runtests.fs
echo | python nuc.py -c 4 -b runtests.fs
echo | python nuc.py -c 8 -b runtests.fs
cd ../x64
sh localtest
cd ../j1a/verilator
sh localtest
cd ../../j1b/verilator
sh localtest
